language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: react-pipeline
  on:
    branch: main
  api_key:
    secure: Dk20LE21RBkuQ82JppB1eDpVAQ944JrT4lstf980TPe8uvtGpdjmrCgcT6i6MlUi70ZnP9Jl24FlDLv19QoOkobDOiHOi3TDpdXvQ0N1K8yzxfEzAuiooHXuoIky2uwvIvfyUc3CXNdHo0dOGIdkHemBT8TttfxCYJuuuBh6fxffvetHnqt2B82lhcW71XM2x3CC1biE6W4C9J7GH3PLBFInW1oWK7kn8pAz56ngdyvyWDAdyK6WtV+5Udd4Z/XK42Dzjh/uftow281jq5QR0EhKGd1m+AMccBwAomBj9ggCIaUphvntiyGHFddEHBaxo+vlNJFA5WEWAnLqlF5OgQ0+xa08Ch1PjeGcYiwiyIbQhcLExClr59YDbgfLcnHWlNNUxg9tvIp4kEJDcY99ETRMrPpJ38j15DtLskwrtsjlAVgIGmOy/CnEI7+6MN6qIC/F+rGB7RUPOVOD2nqbNRqgi0nNOsS/26vgXLZiGMkt2jCzBEwVTyVxU1/pksV7iXyjPanQE4/WYfyG06zysDe4I13SxFoqLzQr3uTV8O22ReY2GZlXg5hrqFj6xq2zTfJeTSWBKgisA/fySiJr15vrLofy/M5mrPd0AObbRIHgaDbYBGVo4co6/qkcXDYx3gvSgXERYan74ZP5ZdZ7vljfsqzlUV/Bpp6M7yv6m84=
