language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: react-
  on:
    branch: main
  api_key:
    secure: hZ+53QnXDmrWYCi9uXnv5R+DVlNPLkxEtnX3wtgY0PfDc5AMnEaDUDRjYQVLr5XEKXAWmvxWznHSpiVxdqsEIGiJ1gVoqDEw5dHvAHSa/JFggDVs0197b4+d4FA7H7dq90hiPFrm6H89PV+r42Nw/cR9K25hFufrRen6PfnaXjWRqkPWd51w1RDwa0HDYvoCyh4StbZ0c+Rd+hBCTws55PS3uYAK6BZrtNDD4YHTJOEAx4GfNvXxN7xyBHf30edENhI0nuMGLNinzqvRHQNSt9jJRzrsy9SYJrkjXhPW1M8/v+qk83XIUdbKapmviQJt6chtG4kGGQkWg13U0MXPpkVGBOe0sZ25auHUL2iTlshsBZUbZ+AvHgXkJ1QNIC6xwRVltmRmPekse3IO9sgmKt0mnfOuzPB+WrU6EI+jXl9wPUaRqwgk801QEsJuG2/Chx3R+k9ACpfKKuGTNRWUvfI43cOfsUmi8qKFUkmBXOqiuxgvxqRPzyaujU8n2QF+xXbLfY87P2mdygzy87GIl40TKguAY/E5pZrLBVLzYjjV75brWhsqV5KYTrU23xyHBe9XsS6TVOv9LtoEsir0hQQCug8KFGywAeWxqJXqzNdT7IFEZ94Re8I6mDdHqUWeHLqwuut4eyFWDLBoQJuKslZVGkBEebhRiyn8KQ58Blc=
