language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: react-
  on:
    branch: main
  api_key:
    secure: ac67XqcrVdPAi6rXYez93W6vIv3HM7imDAS04WkRxDQ0UE+9X+J4nmz9hpyfDBb78JAMD0+QkEL3CHpL06gdghgf1wF+f2xzO1IxTrXGlByhvaf910cpYuJLlhNWESjDoDVb+VR+knvLg/Mpx0OEG6WhEopOeCYjCJjRv6zQJIxjmg4MNO3d9nje4hXHdo9nzjRLQCNUxNPdksoluAy7HBXEx7m+rYevlskYFOt0QuRO433cqO3CSnHVlyCoKCuh9wzjsx/wc7rGUWTyKZNBcfU+N+SSrwLbM0wYYBX+5BDzA1EBeQ1qgteolNN2RiXMQBbL84tR2CQZoir/Ybwe+G6kNCZPgdQphnnFBI/9DAlOVs7JGlS9wsoLosFnF1ENBbqCHWsLeGW46JuURKbtyCS29qCTbfcSRtKQ86vwjdxV0ZULr1eQtFiz2y5RCKcydYOqS/2ynpQ2KAi/X1SdtfMsiBNY+trWYMgpJH+EwgKMnmfC/xOq8X6D5I+lGOPmF4Q9vMoybbESgpC3+jUUV+kih/dYW8kFIoe7IZXKwykLQ+XvIrlztp7WAGSBxUj37go9kB/qTAvK99HTQV+MSmElWycGkMKeAaoTjiEkBxs38vp272n2Ep8rTwfsqlxxxRNlyrxGCAjWU2Xy4kC/tGpQ04qVb4GDnLwX92+oP/c=
