language: node_js
node_js:
- '12'
script:
- npm test
- npm run build
deploy:
  provider: heroku
  app: react-pipeline
  on:
    branch: main
  api_key:
    secure: VI4qVdOLKJxJqv7qrAxW013vbgU7xago2mSvPm2tElNStNaC4ToEgsA6Avmc6gZwAbdNQc4CeV+R9TPJIkOc0/tEicwsklXa4Rw+XF1kycJjsx68UGKQ0TWEsZ1120gVAsenJNsRNOv1cXxnBs1DWal4pLso4lQ9vvthEARoTUsu2iyK5gEGgej7VeF5uUxGWVQIuettJYJJR1VEw9gZnVbjJZXqj4ddFNFVOSmIkHErT3KFzOAcoRqZqor830jGmfwsJoSEd2ienP0bR2jQ8VU6RTpyAiUbXqPuUNBJ/4aK8F/kfIO1+SOnFE2nCa123yf41TzDf5DcEVMA827h40RmZLhoNI8c81k5d0Vfq0MnQhyjYKOdY6JmFEih1+WONUPp+3vsAHzKcsawLMoIj99k/t8HMQ1ZxWAJsLZgGcbywRRw8NZbRjMXBkQ2cudR5+0OXb7rRyWuqlCuq1KE0OJ1z+0r5Yi60+nqi70kt6qPFmrQSXjp05huMumraCdIUqVvxaNhY0UqJHG3eZhXuW+LF0Ca6izILR+vitr431MFPRoZO99BLAhN7LEYIMeBGFO+7BlTYfNhcgnTGrsrnxUcCAO758OA/+zweq4H+XiJJAVwj+7o76OoVH7eBSn7qJXMe5TZUtZ9tQn1ESB7q6X30HcIxkBYYJLPS9aZ2fE=
